/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddWord: typeof import('./src/components/home/AddWord.vue')['default']
    ConditionFilter: typeof import('./src/components/home/overview/ConditionFilter.vue')['default']
    Home: typeof import('./src/components/home/Home.vue')['default']
    Loader: typeof import('./src/components/ui/Loader.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Navbar: typeof import('./src/components/ui/Navbar.vue')['default']
    Overview: typeof import('./src/components/home/overview/Overview.vue')['default']
    Query: typeof import('./src/components/home/Query.vue')['default']
    Tab: typeof import('./src/components/home/Tab.vue')['default']
    VanBackTop: typeof import('vant/es')['BackTop']
    VanButton: typeof import('vant/es')['Button']
    VanCell: typeof import('vant/es')['Cell']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanCollapse: typeof import('vant/es')['Collapse']
    VanCollapseItem: typeof import('vant/es')['CollapseItem']
    VanDivider: typeof import('vant/es')['Divider']
    VanField: typeof import('vant/es')['Field']
    VanFloatingBubble: typeof import('vant/es')['FloatingBubble']
    VanForm: typeof import('vant/es')['Form']
    VanList: typeof import('vant/es')['List']
    VanLoading: typeof import('vant/es')['Loading']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanOverlay: typeof import('vant/es')['Overlay']
    VanPicker: typeof import('vant/es')['Picker']
    VanPopup: typeof import('vant/es')['Popup']
    VanSwipeCell: typeof import('vant/es')['SwipeCell']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
    WordItem: typeof import('./src/components/word/WordItem.vue')['default']
    WordList: typeof import('./src/components/word/WordList.vue')['default']
  }
}
